version: 2

models:
  - name: customer_orders
    description: "Customer orders model"
    columns:
      - name: order_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: customer_id
        description: "ID of the customer"
      - name: order_date
        description: "Date of the order"
      - name: status
        description: "Status of the order order"
      - name: status
        description: "Status of the order order"
        data_tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: first_name
        description: "First name of the customer"
      - name: last_name
        description: "Last name of the customer"