version: 2

models:
  - name: stg_customers
    description: "Customer model"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: first_name
        description: "First name of the customer"
      - name: last_name
        description: "Last name of the customer"
      - name: first_order_date
        description: "Fist order date of the customer. If null the customer have not made an order"
      - name: most_recent_order_date
        description: "Most recent order date of the customer. If null the customer have not made an order"
      - name: number_of_orders
        description: "Number of orders made by customer. If null the customer have not made an order"
  - name: stg_orders
    description: "Orders model"
    columns:
      - name: order_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: customer_id
        description: "ID of the customer"
      - name: order_date
        description: "Date of the order"
      - name: status
        description: "Status of the order order"
        data_tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
sources:
  - name: bigquery
    description: "Source data from our raw database."
    database: esoteric-burner-454212-p8
    schema: Analytics
    tables:
      - name: customers
        description: "Raw customer data before transformation."
      - name: stg_orders
        description: "Raw orders data before transformation."